---
title: "Домашнє завдання №2"
format: html
---

# dplyr: МАНІПУЛЯЦІЇ З ДАНИМИ

::: {.callout-note}
## Нагадування
* Всі маніпуляції з даними необхідно виконувати з використанням синтаксису `tidyverse`.

* Результати роботи оформити у `Quarto`-документі.

* Перед виконанням роботи не забудьте підключити відповідні пакети
:::



1. Завантажити дані в RStudio. Можна використовувати власні дані або дані з інтернету. Для цього використовуйте функції `read_csv()` або `read_excel()`.

2. Провести базові маніпуляції з даними з використанням функцій:

 * `glimpse()`
 * `filter()`
 * `slice()`
 * `arrange()`
 * `select()`
 * `relocate()`
 * `rename()`
 * `mutate()`
 * `group_by()` + `summarise()`
 * `across()`
 * `count()`
 * `case_when()`
 
::: {.callout-tip}
##
Не обов'язково використовувати всі функції, оберіть ті, які потрібні вам для обробки даних.

Згадайте, що для послідовності функцій можна використовувати "пайп" `%>%`
(CTRL + ALT + M) 
:::

3. В якості додаткового (необов'язкового) завдання виконайте процедуру приведення даних до широкого та довго форматів (`pivot_longer()`, `pivot_wider()`.
